name: CI

on:
  push:
    branches: [ master, dev, fedora ]
  pull_request:
    branches: [ master ]
  # Retest weekly to ensure nothing has broken
  schedule:
    - cron: '0 1 15 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# DAHDI not currently built in Fedora-based distros due to missing Azure kernel headers:
# kernel-devel mismatch has been detected. Package provides 6.12.0-0.rc0.20240918git4a39ac5b7d62, but running kernel is 6.8.0-1014-azure

jobs:
  fedora-42:
    runs-on: ubuntu-24.04
    name: Fedora 42
    container: fedora:42
    steps:
      - uses: actions/checkout@v4
      - name: Build DAHDI and Asterisk
        run: |
          ./phreaknet.sh make
          GIT_REPO_PATH=${GITHUB_WORKSPACE} phreaknet install --fast --dahdi --autokvers --drivers --devmode
